#!/bin/bash

TOPDIR=`pwd`
INSTALL_PATH=$TOPDIR/install
PKG_TOOL_PATH=$TOPDIR/xm6xx-tools
PKG_DIRNAME=xm6xx_pkg

PKG_TAR_FILENAME=upgrade.tar.gz
PKG_FINAL_FILENAME=upgrade.bin
PKG_HASHI_FILENAME=hash.txt

#fix me start
EMMC_PATH=$TOPDIR/../../git_workspace/emmc
UPGRADE_SCRIPT_FILE="$PKG_TOOL_PATH/xm6xx_upgrade.sh"
CLASSIFIER_PATH="$EMMC_PATH/data/classifier"
FDRSERVER_FILE="$INSTALL_PATH/fdrserver"
ISP_FILE="$EMMC_PATH/usr/isp"
GUI_PATH="$EMMC_PATH/data/ui"
GUI_EN_PATH="$EMMC_PATH/data/ui-en"
VOICE_PATH="$EMMC_PATH/data/voice"

DEFAULT_CONF_PATH="$EMMC_PATH/data/db"
EMMC_BIN_PATH="$EMMC_PATH/bin"

UPGRADE_JSON_FILE="$TOPDIR/../product/upgrade.json"

UPGRADE_FILE="$UPGRADE_SCRIPT_FILE $UPGRADE_FILE"
UPGRADE_FILE="$CLASSIFIER_PATH $UPGRADE_FILE"
UPGRADE_FILE="$FDRSERVER_FILE $UPGRADE_FILE"
UPGRADE_FILE="$ISP_FILE $UPGRADE_FILE"
UPGRADE_FILE="$GUI_PATH $UPGRADE_FILE"
UPGRADE_FILE="$GUI_EN_PATH $UPGRADE_FILE"
UPGRADE_FILE="$VOICE_PATH $UPGRADE_FILE"

UPGRADE_FILE="$DEFAULT_CONF_PATH $UPGRADE_FILE"
#UPGRADE_FILE="$EMMC_BIN_PATH $UPGRADE_FILE"
#UPGRADE_FILE="$UPGRADE_JSON_FILE $UPGRADE_FILE"

echo "$UPGRADE_FILE"
#fixme end


cd $INSTALL_PATH
rm -f $PKG_TAR_FILENAME $PKG_HASHI_FILENAME $PKG_FINAL_FILENAME
rm -rf $PKG_DIRNAME
mkdir -p $PKG_DIRNAME
cp -rf $UPGRADE_FILE $PKG_DIRNAME/

RETVAL=$?
if [ $RETVAL -ne 0 ]; then
    exit 1;
fi

tar zcvf $PKG_TAR_FILENAME $PKG_DIRNAME

sha256sum $PKG_TAR_FILENAME | awk '{printf $1}' > $PKG_HASHI_FILENAME
cat $PKG_HASHI_FILENAME $PKG_TAR_FILENAME > $PKG_FINAL_FILENAME
#rm -f $PKG_TAR_FILENAME $PKG_HASHI_FILENAME


