#!/bin/bash

TOPDIR=`pwd`
INSTALL_PATH=$TOPDIR/install
PKG_TOOL_PATH=$TOPDIR/xm6xx-tools
PKG_DIRNAME=xm6xx_pkg

PKG_TAR_FILENAME=upgrade.tar.gz
PKG_FINAL_FILENAME=upgrade.bin
PKG_HASHI_FILENAME=hash.txt

#fix me start
UPGRADE_SCRIPT_FILE="$PKG_TOOL_PATH/xm6xx_upgrade.sh"
VRAPP_FILE="$INSTALL_PATH/vrapp"

UPGRADE_FILE="$UPGRADE_SCRIPT_FILE $UPGRADE_FILE"
UPGRADE_FILE="$VRAPP_FILE $UPGRADE_FILE"


echo "$UPGRADE_FILE"
#fixme end


cd $INSTALL_PATH
rm -f $PKG_TAR_FILENAME $PKG_HASHI_FILENAME $PKG_FINAL_FILENAME
rm -rf $PKG_DIRNAME
mkdir -p $PKG_DIRNAME
cp -rf $UPGRADE_FILE $PKG_DIRNAME/

RETVAL=$?
if [ $RETVAL -ne 0 ]; then
    exit 1;
fi

tar zcvf $PKG_TAR_FILENAME $PKG_DIRNAME

sha256sum $PKG_TAR_FILENAME | awk '{printf $1}' > $PKG_HASHI_FILENAME
cat $PKG_HASHI_FILENAME $PKG_TAR_FILENAME > $PKG_FINAL_FILENAME
#rm -f $PKG_TAR_FILENAME $PKG_HASHI_FILENAME


